### ISSUE TITLE
The repaired version still has bug in grep and locate command

### ISSUE THREAD

**Issue by xyz1396** [shenwei356/seqkit#179]
Although there is no error when running the seqkit grep command in the new version. But the hit proteins is half of the old version. Besides, the locate command cannot report the matched sequence properly. The code below can reproduce the bug. I uploaded the file can raise the bug with the output. Thanks for your help!

`./seqkit locate allResultsRaiseBug.fasta \
  -i -m 2 -p TYLKTNLFL \
  -o allResultsRaiseBug.location.txt`

[allResultsRaiseBug.zip](https://github.com/shenwei356/seqkit/files/5871137/allResultsRaiseBug.zip)

**Comment by shenwei356** [comment]
> Although there is no error when running the seqkit grep command in the new version. But the hit proteins is half of the old version.

Use this patch.

> Besides, the locate command cannot report the matched sequence properly. 

Fixed. It's caused by [a bug on handling of queries containing letters not in subject alphabet](https://github.com/shenwei356/bwt/commit/0f625e9ba618d233031ae631f33162508edf78ab). It's previously [appeared](#124) and fixed, the patch was not perfect.

Changes:

  - `seqkit grep`:
      - fix a bug of `-m`. [#178](https://github.com/shenwei356/seqkit/issues/178)
      - onply search on positive strand when searching unlimited or protein sequences.
  - `seqkit locate`:
      - fix bug of `-m` when query contains letters not in alphabet. [#179](https://github.com/shenwei356/seqkit/issues/179)

Binaries:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5872304/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5872314/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/5872315/seqkit_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
@xyz1396  Does the patch work for you?
