### ISSUE TITLE
Seqkit replace with KV file - $ in middle of sequence name

### ISSUE THREAD

**Issue by ammaraziz** [shenwei356/seqkit#243]
### Prerequisites

Version: 2.0.0 (conda)
OS: Linux Mint 20

### Describe your issue

I am trying to rename a sequence file that contains `$` in the middle of name. However, it truncates everything proceeding the `$`. Here's an example:

Fasta file with 'raw' names:

    >Fasta1
    ATGC
    >Fasta2
    ATGC

kv.txt file:

    Fasta1    Fasta1_$_F
    Fasta2    Fasta2_$

Command used:

    seqkit replace my.fasta -p '(.*)' -r '{kv}' -k kv.txt

Expected output:

    >Fasta1_$_F
    ATGC....
    >Fasta2_$
    ATGC....

Current output:

    >Fasta1_
    ATGC....
    >Fasta2_$
    ATGC....

Note that `Fast1` is incorrect, everything after the `$` is dropped. `Fasta2` works if the `$` is at the end.

This is either a bug or my `-p` regex needs correcting. Any advice would be appreciated. 
I realise that `$` is not a great character to use in a fasta header but unfortunately it's a requirement for downstream analysis.

**Comment by shenwei356** [comment]
Internally, there are two replace steps for replacing with KV file:

1. replace `{kv}` with the corresponding value, e.g., `Fasta1_$_F`.
2. replace the sequence name with the replacement string, i.e., `Fasta1` -> `Fasta1_$_F`.

`$` is a special character in regular expression replacement. To insert a literal `$` in the output, we need to use `$$`. 
Since two replacing steps occurred, we need to use `$$$$` here.

1. `{kv}` -> `Fasta1_$$_F`
2. `Fasta1` -> `Fasta1_$_F`.

Command

```
$ seqkit replace my.fasta -p '(.*)' -r '{kv}' -k <(sed 's/\$/$$$$/' kv.txt)
[INFO] read key-value file: /dev/fd/63
[INFO] 2 pairs of key-value loaded
>Fasta1_$_F
ATGC
>Fasta2_$
ATGC
```

**Comment by shenwei356** [comment]
If KV file is not used: 

```
$ seqkit replace my.fasta -p 'Fasta1' -r 'Fasta1_$$_F'
>Fasta1_$_F
ATGC
>Fasta2
ATGC
```

**Comment by ammaraziz** [comment]
Thanks for explaining the internals of `replace`. Adding `$$` for a literal `$` is a good workaround. Thanks for solving this issue! I am going to close this now. 

Also, just wanted to say thanks again for Seqkit it has become part of my regular workflow.
