### ISSUE TITLE
Enhancement: Plot benchmark results with log axes

### ISSUE THREAD

**Issue by corneliusroemer** [shenwei356/seqkit#264]
I tried to look at your benchmarks.

Unfortunately, I can see much, because the axes are linear and not logarithmic.

It could be helpful to put at least time on log axis.

Also, tabular results would be great for accessibility and convenience.

![Screenshot_20211202-170536~2.jpg](https://user-images.githubusercontent.com/25161793/144458973-2c737988-9eaf-49aa-9d46-73c4617e2c7e.jpg)

**Comment by jmonroynieto** [comment]
You can learn more about the benchmarks on the [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0163962) and the [additional data](https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0163962/1/pone.0163962.s001.pdf?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20211202%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20211202T172948Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=10695081d2540378f73907eb3de403410518bdaa71e4cee4bc3764605a725bf4eb29cedbd666ea6534f06cc15d83b3b1bd9f98f10de8ac5214301a6eca721a8f563822904fc51a2fee9937d1d0ec09f1a6b36ac0e3a929496dd2ec95362c20478a769d1733fdee286f64475c50cfb6a07b27a6d47b1d11f2e65ce943339f1c5eee4ffd2047c0cb744bdb7649f46ececbaf5810e210dc48683c5121a3fc383f1c8685ffdc6b78760e1f6053f214a2a88408bf6ddf32d05e3a482270cf6e972e3a847be3d2d6973f54ad501e13eb8333e741373aa943fd48667d4b5ff0e28d95f6ce5d3190b126bb8ee8de04accd98223ca700f73f62680376b7320726ddc24754) see page 9.

**Comment by shenwei356** [comment]
Thank you Juan.

I always provide reproducible [benchmark scripts and results](https://github.com/shenwei356/seqkit/tree/master/benchmark) along with source code. The tabular results are [here](https://github.com/shenwei356/seqkit/blob/master/benchmark/benchmark.5tests.tsv).

And I keep updating the seqkit and have optimized the speed a lot since the publication which was five years ago.  Here's an [FASTA/Q I/O benchmark](https://github.com/shenwei356/bio/tree/master/benchmark/fastx) result between seqkit v2.0.0 and the lastet seqtk.
![](https://github.com/shenwei356/bio/raw/master/benchmark/fastx/benchmark.tsv.png)

Here' another [FASTQ reading benchmark(https://github.com/lh3/biofast/pull/22) with many languages. Where `fqcnt_go2` used my `bio` library.

|app             |gzip  |plain|
|:---------------|:-----|:----|
|fqcnt_needletail|5.924 |0.733|
|fqcnt_c1_kseq   |7.402 |1.115|
|fqcnt_rustbio   |7.413 |2.331|
|fqcnt_nim1_klib |8.059 |1.781|
|*fqcnt_go2*       |8.987 |1.166|
|fqcnt_go1       |23.058|3.534|
