### ISSUE TITLE
command not found: seqkit

### ISSUE THREAD

**Issue by banuelos3** [shenwei356/seqkit#266]
Hi, I am very new to this sorry for my confusion. 
I installed & decompressed seqkit, but when I go to my Mac terminal and use 

seqkit fq2fa reads_1.fq.gz -o reads_1.fa.gz

(I replace reads with my file's name), but I get the output that 

command not found: seqkit

I'm not sure what I'm doing wrong..Please help if you can thank you

**Comment by jmonroynieto** [comment]
Your program needs to be inside a folder that can be found by the terminal to execute programs. This is achieved by putting your program in a directory that is in your PATH variable or by adding the directory to the PATH variable. This variable is just a list of places where your shell(terminal program) searches for executables. If your program is in one of these locations and can't be found is because it does not have permission to run.

See this [article $PATH variable](https://janelbrandon.medium.com/understanding-the-path-variable-6eae0936e976)
If you are just starting out, [this guide](https://guide.bash.academy/inception/) was my favorite resource for command-line usage.

This is a [short introduction](https://medium.com/@peey/how-to-make-a-file-executable-in-linux-99f2070306b5) on permissions, chmod, and executables.

I understand that you are new to all of this. But I should not avoid mentioning that this issue is not a problem with seqkit. For this type of issue, please seek help in forums for general use such as biostars, stack overflow, super user, r/bioinformatics (They have a great slack too where looking for help is very easy ). 

Hope this helps.
