### ISSUE TITLE
Merge seqs

### ISSUE THREAD

**Issue by zhichusun** [shenwei356/seqkit#277]
How to merge many seqs in a fasta file into one seq, I am a novice, thank you for someone who can tell me.

**Comment by jmonroynieto** [comment]
The way I would do it involves several redirections you can learn about those [here](https://www.redhat.com/sysadmin/redirect-operators-bash) and [here](https://www.gnu.org/software/bash/manual/html_node/Redirections.html).

This is an example fasta file `t.fa`:
```
>test
ACCTGATGT
>test2
TGATAGCTACTAGGGTGTCTATCG
```
The following command extracts the first fasta identifier of the file, extracts all sequences, joins them with `tr` and they are then passed to Seqkit for formating. If you want to use some other approach to select the final identifier, modify the first pair of parentheses (a subshell).

Normally line length is 80 but I used 10 because the example is so small.
```
cat  <(echo -e -n ">"; seqkit seq -n t.fa | head -n 1) <(seqkit seq -w0 -s t.fa | tr -d '\n') | seqkit seq -w 10
```

output is
```
>test
ACCTGATGTT
GATAGCTACT
AGGGTGTCTA
TCG
```
