### ISSUE TITLE
Strange grep regex behavior

### ISSUE THREAD

**Issue by photocyte** [shenwei356/seqkit#318]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Hi there, I'm having an issue with a `seqkit grep` regex that is matching more broadly than I think it should. Example below. Do you know why it is matching the extra fasta record?

**Input:**
```
echo ">12B1-Scaf17:2321226-2423444:._+_64465_64488_GAGACGCCGCTGATGGAGGCCGG;1Gs
GAGACGCCGCTGATGGAGGC
>12B1-Scaf17:2321226-2423444:._+_62008_62031_CGACGTGCTCACGCTGCGGCGGG;1Gs
CGACGTGCTCACGCTGCGGC" | seqkit grep --ignore-case -s -r -p '"^G{1,1}[ATC]{1,1}"'
```

**Actual output:**
```
>12B1-Scaf17:2321226-2423444:._+_64465_64488_GAGACGCCGCTGATGGAGGCCGG;1Gs
GAGACGCCGCTGATGGAGGC
>12B1-Scaf17:2321226-2423444:._+_62008_62031_CGACGTGCTCACGCTGCGGCGGG;1Gs
CGACGTGCTCACGCTGCGGC
```

**Expected output:**
```
>12B1-Scaf17:2321226-2423444:._+_64465_64488_GAGACGCCGCTGATGGAGGCCGG;1Gs
GAGACGCCGCTGATGGAGGC
```

**Comment by shenwei356** [comment]
Because `seqkit greq -s` searches both strands by default since v2.0.0, and the reverse complement sequence of `GAGACGCCGCTGATGGAGGC` is `GCCTCCATCAGCGGCGTCTC`, which is matched.

```
  2. When searching by sequences, it's partly matching, and both positive
     and negative strands are searched.

  -s, --by-seq                 search subseq on seq, both positive and negative strand are searched, and mismatch allowed using flag -m/--max-mismatch
```

Just add `-P`

```
  -P, --only-positive-strand   only search on positive strand
```

v2.0.0 Breaking changes
 - seqkit grep/rmdup/common: consider reverse complement sequence by default for comparing by sequence, add flag -P/--only-positive-strand. https://github.com/shenwei356/seqkit/issues/215
