### ISSUE TITLE
Intermittent locate error "index out of range [-1]"

### ISSUE THREAD

**Issue by bbremer** [shenwei356/seqkit#321]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
I'm getting the following error maybe one out of every 50 runs of `seqkit locate -f <pattern file> -F -j 16 -m 2 <input file>`, where `<pattern file>` and `<input file>` are constant:

> Locate stderr:
panic: runtime error: index out of range [-1]

> goroutine 262497 [running]:
github.com/shenwei356/bwt.FromSuffixArray(...)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/bwt@v0.6.0/bwt.go:101
github.com/shenwei356/bwt/fmi.(*FMIndex).Transform(0xc001ed6160, {0x122b608, 0x0, 0x40d9c7?})
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/bwt@v0.6.0/fmi/fmi.go:59 +0x565
github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func16.2(0xc001ecc230, 0xaad4)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/locate.go:405 +0x450
created by github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func16
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/locate.go:371 +0x318a

Error occurs with both v2.1.0 and v2.3.0.

* [❌] provide a reproducible example
No data reproduces this reliably. A colleague is currently generating non-confidential data, but there's no guarantee that this data will result in the error at a reasonable rate or at all.

Intermittent error with the same data and conditions suggests a race condition to me, but I'm certainly not an expert in Golang.

**Comment by shenwei356** [comment]
This bug was triggered by empty sequences. The [bwt(https://github.com/shenwei356/bwt) package failed to detect this boundary case, and it's fixed now. The `seqkit grep/locate` command now also directly skip these sequences.

Thanks for reporting this. Please use the patches below before the next release.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/9379316/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/9379319/seqkit_linux_amd64.tar.gz)
