### ISSUE TITLE
seqkit split with pair of FASTQ and check pair-endness

### ISSUE THREAD

**Issue by avilella** [shenwei356/seqkit#35]
This is a feature request for seqkit, which I am exploring for some of our production pipelines:

Would it be possible to have the seqkit command split pairs of FASTQ files in n parts, but checking that the pair-endness of file1 and file2 is kept for each file? E.g. something like:

```
seqtk splitpe -1 Sample1_S1_L001_R1_001.fastq.gz -2 Sample1_S1_L001_R2_001.fastq.gz -p 4 -j 4
```

The current implementation is useful, but memory intensive for FASTQ (since two-pass mode does not support FASTQ format), and does not check for pair-endness after splitting the files, since it has to be done one file at a time, and the pair-endness would have to be checked with an external tool like `seqtk mergepe`.

**Comment by shenwei356** [comment]
Maybe I should have written with the easy and straightforward strategy for splitting whatever sequence format (PE/SE fastq or fasta) by whatever way (N parts, N records one file, or one unique ID/subseq for one file). The biggest drawback is limited splitted files due to the limit of opened file descriptors, and these are workarounds **in cost of speed**.

```
fh_map = map (key: file-handler)
for a record:
    key of a record (ID/subseq/Nth part))
    write record to fh_map[key]
```

I'll rewrite `seqkit split` when I'm free.

**Comment by shenwei356** [comment]
Hi @avilella , sorry for the late reply.

I've just added a new command `seqkit split2`, which can also handle FASTA and single-end FASTQ, so I did not name it `seqkit splitpe`. `seqkit split` is remained for compatibility.

Please try it: [v0.9.0-dev](https://github.com/shenwei356/seqkit/releases/tag/v0.9.0-dev)

**Comment by avilella** [comment]
Thanks!
