### ISSUE TITLE
Chain subcommands/operations

### ISSUE THREAD

**Issue by fungs** [shenwei356/seqkit#38]
Hi, this is a simple feature suggestion which might be easy to implement and would speed up usage even further. I sometimes end up chaining different operations of seqkit using shell pipes. However, this involves serialization and deserialization with each pipe which is actually unnecessary. What about allowing to chain operations on the seqkit command line by doing:

    seqkit -general-opts sub_command1 -opt1 ... sub_command2 -opt2 ...

I don't know how you pass sequence objects internally but if there is a general representation this should be no more than adjusting the command line parsing.

Keep up the good work, this is a brilliant piece of software!

Best,
Johannes

**Comment by shenwei356** [comment]
Hi Johannes,

Thanks for your suggestion. Like shell commands including`cut`, `head`, `awk` and `sed`, `seqkit` provides many separated commands with specific functions, they can be piped (chained) to accomplish complex operations. 

Modularization makes development and using more easier. while chaining multiple subcomands internally would significantly increase the development complexity. And since FASTA/Q parsing of `seqkit` is very fast, command line pipe is efficient enough.　

Sincerely,
Wei

**Comment by fungs** [comment]
You are probably right, the gain could only be marginal. I just noted having up to 5 subcommands chained for large data streams, which seemed a little awkward to me.

**Comment by shenwei356** [comment]
What are the 5 subcommands?

**Comment by fungs** [comment]
I don't remember exactly, probably some combination involving grep, replace (to rename sequence names by regexp), rmdup, subseq, and shuffle.

**Comment by shenwei356** [comment]
Ha ha, that's common. Thanks for using seqkit.
