### ISSUE TITLE
seqkit 2.5.0 reports wrong version number (2.4.0)

### ISSUE THREAD

**Issue by mwittchen** [shenwei356/seqkit#404]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
Seqkit version 2.5.0 reports as version 2.4.0 when invoking `seqkit version`
* [x] provide a reproducible example
download seqkit version 2.5.0 (linux Amd64 Bit) [not tested with other versions]
run `seqkit version`

**Comment by photocyte** [comment]
I also ran into this issue. I believe it is because the links on the release page are pointing to the wrong version:
https://github.com/shenwei356/seqkit/releases/tag/v2.5.0 

If you select the `macOS arm64` one for example, it points to 
https://github.com/shenwei356/seqkit/releases/download/v2.4.0/seqkit_darwin_arm64.tar.gz

not
https://github.com/shenwei356/seqkit/releases/download/v2.5.0/seqkit_darwin_arm64.tar.gz

The executable inside the `v2.5.0` package is reporting v2.5.0 for me.

**Comment by shenwei356** [comment]
Oh, such a stupid mistake I've made. I forgot to update the download links ... just fixed it ...
