### ISSUE TITLE
how to replace `n` to `-`?

### ISSUE THREAD

**Issue by liamxg** [shenwei356/seqkit#452]
Dear @shenwei356,

Could you tell me how to replace `n` to `-` for fasta format file?

**Comment by shenwei356** [comment]
https://bioinf.shenwei.me/seqkit/usage/#replace

I'm not sure what do you mean? N's in sequences?

    seqkit replace -s -i -p N -r "-"

**Comment by shenwei356** [comment]
Yes. Please also read the usage and examples.

**Comment by shenwei356** [comment]
Because there's no spaces or other special characters in it, then the shell would handle it properly, eight in `N`, `'N'`, or `"N"`.

For a variable, if you want to pass its value, use double quotes or itself, like `head -n $n` or `head -n "$n"`.
But if you want to pass a special character, use single quote `'$n'`, or a backslash to escape it `"\$n"`.

**Comment by shenwei356** [comment]
> seqkit replace -s -i -p N -r "-"

Here,  `-i` helps to ignore the cases, which means both `N` and `n` will be replaced.

```
  -i, --ignore-case              ignore case
```

Please read the usage and try it with a simple test. https://bioinf.shenwei.me/seqkit/usage/#replace
