### ISSUE TITLE
v0.9.2 not dealing with empty files

### ISSUE THREAD

**Issue by jwasmuth** [shenwei356/seqkit#57]
Not sure if I should have reopened https://github.com/shenwei356/seqkit/issues/36.

I'm getting the following error when running seqkit (v0.9.2) stats on an empty file.

>     panic: runtime error: invalid memory address or nil pointer dereference
>     [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x767eee]
> 
>     goroutine 7 [running]:
>     github.com/shenwei356/bio/seq.(*Alphabet).String(...)
>     /home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/bio/seq/alphabet.go:213
>     github.com/shenwei356/seqkit/seqkit/cmd.glob..func24.3(0xc0001647e0, 0xc0000121c0, 0x1, 0x0, 0x839d04, 0xc, 0xc0000be780, 0xc0000a1860, 0x0, 0xc0001647d0, ...)
>     /home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:375 +0xa9e
>     created by github.com/shenwei356/seqkit/seqkit/cmd.glob..func24
>     /home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:281 +0x8d2

Thanks
James

**Comment by shenwei356** [comment]
Dear James, it is a bug, and  I've fixed it. Try this pre-release:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2623761/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2623762/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2623763/seqkit_windows_amd64.exe.tar.gz)

```
$ ls -lh  *.fx
-rw-r--r-- 1 shenwei shenwei 1 11月 28 17:32 blank1.fx
-rw-r--r-- 1 shenwei shenwei 2 8月  15 00:46 blank.fx
-rw-r--r-- 1 shenwei shenwei 0 8月  15 00:46 empty.fx

$ for f in *.fx; do echo ---[ $f ]---; cat -A $f; done
---[ blank1.fx ]---
$
---[ blank.fx ]---
 $
---[ empty.fx ]---
$ seqkit stats *.fx
[ERRO] blank.fx: fastx: invalid FASTA/Q format
[shenwei@BioS tests]$ seqkit stats *.fx -e
[WARN] blank.fx: fastx: invalid FASTA/Q format
file       format  type  num_seqs  sum_len  min_len  avg_len  max_len
blank1.fx                       0        0        0        0        0
empty.fx                        0        0        0        0        0

```

Since v0.8.0, seqkit require the data steam must starting with `>` or `@`, so it report error for the `blank.fx` heading with space. And you can use flag `-e/--skip-err` to skip non-FASTA/Q files.

**Comment by jwasmuth** [comment]
Thanks. It works for me.
