### ISSUE TITLE
Tabs in header not parsed correctly

### ISSUE THREAD

**Issue by FlyinTeller** [shenwei356/seqkit#78]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
When I have a tab character seperating my ID from the rest of the header, it is not correctly renamed
* [x] provide a reproducible example

Contents of `test.fasta` (blanks are single `\t ` characters):
```
>4	1234-12
ACGTAGGTA
>4	12345-12
AGTAAGGTA
```
Different calls and output:
```
$ ./seqkit.exe rename test.fasta #Expect detection of duplicate "4" ID
>4      1234-12
ACGTAGGTA
>4      12345-12
AGTAAGGTA
```
Expected result was of course that the duplicate entry "4" would be renamed, as the default regexp 
`"^([^\\s]+)\\s?"` should only math the `4`

This should be equivalent (as `\S` is `^\s`), but gives the actual, expected result where the `4` is correctly renamed:
```
$ ./seqkit.exe rename test.fasta  --id-regexp "^([\\S]+)\\s?"
>4      1234-12
ACGTAGGTA
>4_2 4  12345-12
AGTAAGGTA
```

My conclusion would be that there is something not working as expected with the default regexp. Could you shed some light what it might be?

**Comment by shenwei356** [comment]
Because parsing FASTA ID using regular expression is slow, I used [a more efficient way](https://github.com/shenwei356/bio/blob/f563cf8d95a93f922d43b1ee8dfbfc6f325ff5e2/seqio/fastx/reader.go#L377) for default case, by finding the first space while forgot tab. I've [fixed this](https://github.com/shenwei356/bio/blob/master/seqio/fastx/reader.go#L377).

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3442771/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3442776/seqkit_darwin_amd64.tar.gz)
- [seqkit_windows_386.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3442772/seqkit_windows_386.exe.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3442773/seqkit_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
And I've simplify the [regexp](https://github.com/shenwei356/bio/blob/master/seqio/fastx/reader.go#L62) to `^(\S+)\s?`, thank you.

**Comment by FlyinTeller** [comment]
Thank you for your swift reply. Any chance you could upload the most current version to the anaconda channel?

**Comment by shenwei356** [comment]
Maybe tomorrow.

**Comment by shenwei356** [comment]
available on bioconda
